# Generated by Django 3.2.8 on 2021-10-23 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='TaskKyuLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_level', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.CreateModel(
            name='TypeTaskCodeWars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Тип задачи',
                'verbose_name_plural': 'Типы задач',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=128)),
                ('code_wars_username', models.CharField(default='', max_length=64)),
                ('progress', models.FloatField(blank=True, default=0, max_length=8)),
                ('member_division', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CodeWarsHelper.subdivision')),
                ('member_group', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CodeWarsHelper.group')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='CodeWarsTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_task', models.CharField(max_length=128)),
                ('kyu_level', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CodeWarsHelper.taskkyulevel')),
                ('type_task', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CodeWarsHelper.typetaskcodewars')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
