# Generated by Django 3.2.8 on 2021-10-23 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeWarsHelper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='codewarstasks',
            table='code_wars_tasks',
        ),
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
        migrations.AlterModelTable(
            name='members',
            table='members',
        ),
        migrations.AlterModelTable(
            name='subdivision',
            table='subdivision',
        ),
        migrations.AlterModelTable(
            name='taskkyulevel',
            table='task_levels',
        ),
        migrations.AlterModelTable(
            name='typetaskcodewars',
            table='type_tasks',
        ),
    ]
